apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: alertmanager-templates
  namespace: episilia
data:
  default.tmpl: |
    {{if eq .Status "firing"}}*FIRING ALERT* - {{.Alerts.Firing | len}}{{else}}*RESOLVED ALERT*{{end}}
    
    *Alert Name:* {{.CommonLabels.alertname}} for {{.CommonLabels.job}}
    
    {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
    ({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ range $index, $label := .SortedPairs }}{{ if $index }}, {{ end }}{{ $label.Name }}="{{ $label.Value }}"{{ end }}{{ end }})
    {{- end }}
    
    {{range .Alerts -}}
    *Alert:* {{.Annotations.title}}{{if .Labels.severity}} - `{{.Labels.severity}}`{{end}}
    *Description:* {{.Annotations.description}}
    *Details:*
    {{range .Labels.SortedPairs}}*{{.Name}}:* `{{.Value}}`
    {{end}}
    {{end}}