kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: episilia
data:
  config.yml: |-
    global:
      resolve_timeout: 1m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'episilia@episilia.com'
      smtp_auth_username: 'episilia@episilia.com'
      smtp_auth_identity: 'episilia@episilia.com'
      smtp_auth_password: 'abcd1234'

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 24h
      receiver: 'email'

    receivers:
    - name: 'email'
      email_configs:
      - to: 'episilia@91social.com, episilia@gmail.com'
        send_resolved: true

