kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: episilia
data:
  config.yml: |-
    global:
      resolve_timeout: 10s
      slack_api_url: 'https://hooks.slack.com/slack-web-hook'
    route:
      group_by: ["alertname"]
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 10s
      receiver: "slack-notifications"
    receivers:
      - name: "slack-notifications"
        slack_configs:
          - channel: "#Slack-Channel"
            username: "Episilia_Alerts"
            send_resolved: true
            title: '{{ if eq .Status "firing" }}*Alert:*{{ else }}*Resolved:*{{ end }} {{ .CommonLabels.alertname }}'
            text: |-
                {{ template "default.tmpl" . }}
    templates:
      - '/etc/alertmanager/templates/default.tmpl'

    inhibit_rules:
      - source_match:
          severity: "critical"
      - target_match:
          severity: "warning"
        equal: ["alertname", "dev", "instance"]