apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: episilia
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '5050'
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.49.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-admin-api"
            - "--web.listen-address=:5050"
          ports:
            - name: web
              containerPort: 5050
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-server
        - name: prometheus-storage-volume
          emptyDir: {}
