apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: episilia
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters, and output
  # =======================================================
    fluent-bit.conf: |
      [SERVICE]
        Flush         5
        Log_Level     debug
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        # Plugins_File /fluent-bit/etc/plugins.conf

      @INCLUDE input-kubernetes.conf
      @INCLUDE filter-kubernetes.conf
      @INCLUDE output-kafka.conf

    input-kubernetes.conf: |
      [INPUT]
        Name            tail
        Path            /var/log/containers/*{namespace}*.log
        Key             message
        Parser          default
        Path_Key        file
        Tag             kube.*
        Mem_Buf_Limit   5MB
        Skip_Long_Lines On
        Read_from_head  true

    output-kafka.conf: |
      [OUTPUT]
        Name                  s3
        Match                 *
        bucket                <bucket-name>
        region                <region>
        s3_key_format         /<folder-name>/$TAG[4]/%Y%m%d/%H/$UUID.gz
        endpoint              <s3-endpoint>
        total_file_size       5M
        upload_timeout        1m
        use_put_object        On
        compression           gzip
        static_file_path      On
        json_date_key         timestamp
        json_date_format      iso8601
        
    parsers.conf: |
        [PARSER]
          Name        default
          Format      regex
          Regex       ^(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}) - (?<message>.*)$
          Time_Key    time
          Time_Format %Y-%m-%d %H:%M:%S,%L
          Time_Keep   On