apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: episilia
spec:
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
      name: http
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: minio
  type: NodePort